#!/usr/bin/env bash
# This script adds a Debian package to the repository

# Defaults
export REPREPRO_BASE_DIR=/var/local/repo

# Where are the packages we need to add to repository?
[ -z "${BUILD_RESULTS}" ] \
    && BUILD_RESULTS=`pwd`'/../build_results'

# Get $BUILD_ARCH, $DIST and $RELEASE from the content of the source package
. ./check-release-repo.sh ${BUILD_RESULTS}
[ $? -eq 0 ] || exit 1

# Add resulting packages to local repository
reprepro --waitforlock 12 -v includedsc ${RELEASE} ${BUILD_RESULTS}/*.dsc
for c in `ls ${BUILD_RESULTS}/*_[^s][a-z]*.changes`; do
    reprepro --waitforlock 12 -v include ${RELEASE} $c
done

# Run Lintian on built package
for c in `ls ${BUILD_RESULTS}/*_*.changes`; do
    lintian --suppress-tags bad-distribution-in-changes-file $c
done

