#!/usr/bin/env bash
# This script adds a Debian package to the repository

# Defaults
export REPREPRO_BASE_DIR=/var/local/repo
BUILD_RESULTS='/mnt/build/build_results'

# Get $BUILD_ARCH, $DIST and $RELEASE from the content of the source package
./check-release-repo.sh ${BUILD_RESULTS}
[ $? -eq 0 ] || exit 1

# Add resulting packages to local repository
reprepro --waitforlock 12 -v includedsc ${RELEASE} ${BUILD_RESULTS}/*.dsc
reprepro --waitforlock 12 -v include ${RELEASE} ${BUILD_RESULTS}/*.changes

# Run Lintian on built package
lintian --suppress-tags bad-distribution-in-changes-file ${BUILD_RESULTS}/*.changes

