#!/usr/bin/env bash
# This script adds the Debian packages produced by Unibuild
# to a given APT repository managed with reprepro.
# Arguments:
#  $1: the directory containing packages built with Unibuild
#  $2: the release repository where to store the packages

# Checks args
if [ $# -lt 2 ]; then
    echo "We need two args:"
    echo "  \$1: directory containing packages"
    echo "  \$2: release repository"
    exit 1
fi
BUILD_RESULTS=$1
RELEASE=$2

# Defaults
export REPREPRO_BASE_DIR=/var/local/repo

# Add resulting packages to repository
# If multiple .changes files exist for the same package, only the most recent one will be kept
for changes in `ls ${BUILD_RESULTS}/*.dsc`; do
    reprepro --waitforlock 12 -v includedsc ${RELEASE} $changes
done
for changes in `ls ${BUILD_RESULTS}/*_[^s][a-z0-9]*.changes`; do
    reprepro --waitforlock 12 --ignore=wrongdistribution -v include ${RELEASE} $changes
done

# Also add standalone .deb packages resulting from multiarch builds
for os in d10 d11 u20 u22; do
    for p in `ls *-${os}_* 2>/dev/null`; do
        reprepro --waitforlock 12 -v includedeb ${RELEASE} $p
    done
done

# Run Lintian on built packages
for changes in `ls ${BUILD_RESULTS}/*.changes`; do
    lintian --suppress-tags bad-distribution-in-changes-file $changes
done

