# Docker compose file dedicated to Unibuild builds
version: '3.9'

###
# Some repeated defaults:
# tmpfs and /sys/fs/cgroup volumes are needed for systemd to work properly
# /app is where the git repositories will be shared with the host
###
x-tmpfs:
  &default-tmpfs
  - /run
  - /run/lock
  - /tmp

x-volumes:
  &default-volumes
  - ${DIR_TO_BE_BUILT}:/app
 
services:
  alma8:
    image: ghcr.io/perfsonar/unibuild/alma8:latest
    volumes: *default-volumes
  alma9:
    image: ghcr.io/perfsonar/unibuild/alma9:latest
    volumes: *default-volumes
  centos7:
    image: ghcr.io/perfsonar/unibuild/centos7:latest
    volumes: *default-volumes
  d10_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/d10:debian-tarball@sha256:8c2f891f38bc83a966ef729d5fb8a5155d36e97520225db16a46711c2707a2cd
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d10_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/d10:debian-tarball@sha256:6e9b1f279075f2823087ac15b33c0504c7ee8478b1ca849d1da8865b17ff4a15
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d10_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/d10:debian-tarball@sha256:41439cfcfc65711e542fc2f40f1506dceaaa1ee6b8e8b01a51208e2a752cf5f5
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d10_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/d10:debian-tarball@sha256:f5b9619d24f6783d5b6187f6d716aa0992358bd42cfea62c088fb9479769d632
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u18_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u18:debian-tarball@sha256:24672ba37a256f0c9b9fa8520102c6cc0ea93c29a9c1e7880fd5f23a9afb93ad
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u18_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/u18:debian-tarball@sha256:1d691c7f850ce432b4a0ed842f071ffe54102648bb902d58c498a72cb2377076
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u18_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u18:debian-tarball@sha256:90b6019448dbf70f12e295b72f8cb0dbb5555962c950fdac5c8b7e738487a4a4
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u18_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u18:debian-tarball@sha256:fb6fbab5f7cc79b4315c3130e19fc6a804ce5b3d0a695c0d72856c890e4e4d70
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u20_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u20:debian-tarball@sha256:e3741642730852d0c65731e8bb18f67581d121087e3adfb275b4af62c7b0cf7b
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u20_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/u20:debian-tarball@sha256:c13c064c17b823726fb7f7122246972c49319004706ba98b22fe581b1d45297b
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u20_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u20:debian-tarball@sha256:a5d75cac5f7776793190d231739c88c795b41ce4cdad184f284dac54d6cafdd6
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u20_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u20:debian-tarball@sha256:91b4e5f0f1c8c5c561f6e2106963e157518ba88c1b4c4f08bd5d286f2b99b49f
    command: bash -c "sleep infinity"
    volumes: *default-volumes

