# Docker compose file dedicated to Unibuild builds

###
# Some repeated defaults:
# tmpfs and /sys/fs/cgroup volumes are needed for systemd to work properly
# /app is where the git repositories will be shared with the host
###
x-tmpfs:
  &default-tmpfs
  - /run
  - /run/lock
  - /tmp

x-volumes:
  &default-volumes
  - ${DIR_TO_BE_BUILT}:/app
 
services:
  el7:
    image: ghcr.io/perfsonar/unibuild/el7:latest
    volumes: *default-volumes
  el8:
    image: ghcr.io/perfsonar/unibuild/el8:latest
    volumes: *default-volumes
  el9:
    image: ghcr.io/perfsonar/unibuild/el9:latest
    volumes: *default-volumes
  d10_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/d10:latest@sha256:e387cf4fc5dc4d6104321bc89f632094b81b617e50edfeb6f7e17c09cab43bf2
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d10_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/d10:latest@sha256:5ad9c712166aa1c5ce274ccdd752163bc2e90a836238ec657147cde23998eb73
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d10_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/d10:latest@sha256:e7cc1837ef7dac74894d8bddf545911a6cb236bfe8002f5ca353146636d5115b
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d10_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/d10:latest@sha256:5b1171293e107a83c89d459097fc533d763bacbb0ac7ec47140fadefeb148b33
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d11_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/d11:latest@sha256:cd95a8cd23c4f6d4841106bb062caa1b0c0915a2788ffa254c25b9156a8d3d86
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d11_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/d11:latest@sha256:c1a499af6a5d8fdd08aa93a8630ae4c22842a4090bd5332287fc8f57be017df7
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d11_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/d11:latest@sha256:9e9f9083b382e6a3f33db9936a34d481abb0e0110bfbc3de7f7e4717cbcd1e8b
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d11_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/d11:latest@sha256:442b6c14a10a471122112ba8fa43da82f443866980709cd21de85ebe073b26e3
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d12_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/d12:latest@sha256:0d619afed56b3f5e707c0a449bddc328f258e6b964decb4560193e584a5c7f74
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d12_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/d12:latest@sha256:8cd1661b3ac2006ae8e782a3d766bc36d8fae8ed77c8ba333828f6129eb861eb
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d12_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/d12:latest@sha256:37c635771f9eda2cde578f8f761a7d0a7166996717bb1845a93328b6a1e387bb
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d12_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/d12:latest@sha256:5c90bc35a594998a9110c537d83929f8dadcf874766bda60921f92ebde9c11ca
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u18_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u18:latest@sha256:e96b8f9408ae32c8e96bd10d5cf5a0c859ede033de75ca24baf1ac486eb4e41b
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u18_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/u18:latest@sha256:bf51d915e9df102707cd3db11e7fead8e37aa23a34a67fd136ca69f9cbb512a1
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u18_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u18:latest@sha256:daba0f2932874c69e106fbc2178eefa4339bc1d818e839c6ce2f7fadd6c23aa4
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u18_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u18:latest@sha256:541c3a4eb042ea19c65ab4c4158ff0543da054cd0d896887e93738c5c9453914
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u20_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:61a4d21ecc6b5fdee30fad65a08fe27cff4d4ef4c58155373035e01796e87306
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u20_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:7ae9c0503a0c15e6c5a030b093b4c87a05e2718d03da16e2124c1f2cb867c1fc
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u20_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:62dcfb52ff9cfa369ca9df45d3ec6d5e7501b01fc4494c5ff57483428fcdff54
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u20_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:c4ba553e5dee57104e5d33a0839c90c2ec058dbbbbffc701efc6418aec54958d
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u22_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u22:latest@sha256:8d86b2819769e1b839cf2fc87dcb891b8d9d9e430e95b864b7fcab2225bebc7e
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u22_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/u22:latest@sha256:c0484aa319674105f30129525b8b4f96b5db32a6294c5f6789e355d51c12273c
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u22_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u22:latest@sha256:530b999b22d096b4008bacee3f8a93c94baacc9584f1cd48ef8267085c767244
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u22_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u22:latest@sha256:8b11709378532debc446179dc5ffd42bd591a1329233c161a9caa329ee26c4d3
    command: bash -c "sleep infinity"
    volumes: *default-volumes

