# Docker compose file dedicated to Unibuild builds
version: '3.9'

###
# Some repeated defaults:
# tmpfs and /sys/fs/cgroup volumes are needed for systemd to work properly
# /app is where the git repositories will be shared with the host
###
x-tmpfs:
  &default-tmpfs
  - /run
  - /run/lock
  - /tmp

x-volumes:
  &default-volumes
  - ${DIR_TO_BE_BUILT}:/app
 
services:
  el7:
    image: ghcr.io/perfsonar/unibuild/el7:latest
    volumes: *default-volumes
  el8:
    image: ghcr.io/perfsonar/unibuild/el8:latest
    volumes: *default-volumes
  el9:
    image: ghcr.io/perfsonar/unibuild/el9:latest
    volumes: *default-volumes
  d10_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/d10:latest@sha256:7f2a1f72f0edff06968b5868d36c741368d407062f651e6f7cb3650290eb9e7f
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d10_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/d10:latest@sha256:d90ff6846b590d3aefda73f6ae2c34223da57ee9874455e2d9b5e8bf2355a8c2
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d10_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/d10:latest@sha256:0a29ed8ac8d03f091712e52994f75e8aab53128017ca9f7c7f8afc852e69a0a5
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d10_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/d10:latest@sha256:848f8b07e06da65b00ce1535decc42715a1eef8fb934b35241053f1bb60c2772
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d11_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/d11:latest@sha256:294a6f61c74c8b06b882727a5d4e7766800b30224bcfff7894b61c8c12263db9
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d11_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/d11:latest@sha256:09db14decbcb10b34b0d972125ac5d4b4b9b03c8c12c2e8a9e39e1c46f87e19c
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d11_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/d11:latest@sha256:8c537f8264516c4a186279bbe4749770ab8b6bf30b22353be30b7b34ca8144b0
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d11_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/d11:latest@sha256:356e1b6c01ddd35bc3755436b2f02a1fd2bb6db69322b3d97e7f0578adf0f9f4
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d12_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/d12:latest@sha256:c997a850c680618e1144f768b6c63554674f32661497caf59453373ab5e5380e
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d12_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/d12:latest@sha256:ec5ec81134b3e6c2fd7c05e41ce0de7658cff72b3469e5730cf08b9438b6f88f
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d12_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/d12:latest@sha256:398663da0155394e53facb08cc180fe3e887977067fee41b441d849c8a2dfa16
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d12_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/d12:latest@sha256:2e9b0ef332762cebfb483118a3f63d3a69937221775a6d431aa59897f68c810d
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u18_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u18:latest@sha256:6d1a63ad0f28977628a5dcd2a3e0863def52653af8e28af717e7354157ad0b43
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u18_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/u18:latest@sha256:18d3e3a4d67511e9d62a07df09bd978695dc3e489bffdc0d4f3e8d954091c1f9
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u18_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u18:latest@sha256:d32be1ca55a19edb625eec65c76b86d0f2d77f4022364e38aca141ecee4d9b97
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u18_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u18:latest@sha256:bd6e7d1d9d9e78eefccde5d0f0159c67d87189b5fe4c2bc8f03df79e591d846e
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u20_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:673668b6e80b29298dc1fbf8894f6807069706f524dc86375f94a2b6979281ad
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u20_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:b4415fe6ed798fbf3e4151a12252f87dbf9dd943840c6c5990929a694cceb75f
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u20_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:bcf1e9c6d7f0c030c65ec92d158c208ac808fd24b10687ffecbb27572acb0636
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u20_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:3a66c3bce2bfb62ca4a9980e0df620d80a047295426f5d7b8730789a71c87b82
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u22_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u22:latest@sha256:fb8929d1964cb865b38ec373c0ecd0425fa45fb448fb7fdf585c66d30e0df96b
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u22_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/u22:latest@sha256:4272f7484c9ced44f64ac1f6ebf898a33be07c5aaa33f8432f5c27ac027135ea
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u22_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u22:latest@sha256:16eff9c56266af70becc11576ce8d116d3577d89d80fec43c16edc19b5af31d8
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u22_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u22:latest@sha256:f5a90ca9a0fde4eed2a0fb9bac1ff237ec74c89ed68340e9c274498288b1a0cc
    command: bash -c "sleep infinity"
    volumes: *default-volumes

