# Docker compose file dedicated to Unibuild builds
version: '3.9'

###
# Some repeated defaults:
# tmpfs and /sys/fs/cgroup volumes are needed for systemd to work properly
# /app is where the git repositories will be shared with the host
###
x-tmpfs:
  &default-tmpfs
  - /run
  - /run/lock
  - /tmp

x-volumes:
  &default-volumes
  - ${DIR_TO_BE_BUILT}:/app
 
services:
  alma8:
    image: ghcr.io/perfsonar/unibuild/alma8:latest
    volumes: *default-volumes
  alma9:
    image: ghcr.io/perfsonar/unibuild/alma9:latest
    volumes: *default-volumes
  centos7:
    image: ghcr.io/perfsonar/unibuild/centos7:latest
    volumes: *default-volumes
  d10_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/d10:latest@sha256:8ba4798c686ac2d69441c005a425461dde9607afa3b988b6e84c52923cfacfba
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d10_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/d10:latest@sha256:eb2b6cf30676e7797cfd03e4b9ce95cdaf2e80df8c3ddd34c003c803a2b48777
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d10_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/d10:latest@sha256:917c291a46fb5405e4f932632b3c8b00212dc0afe2945908ad5d2616ca652aef
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d10_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/d10:latest@sha256:b169497ae5027b2b885f38fde983f0391c7e8f1889297f5e09e13bc25577280e
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u18_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u18:latest@sha256:7fe936b01287c13d71ad75e2110ba2c18a5705f2c4b4488ab48516e499b82317
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u18_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/u18:latest@sha256:6bbe4660c71258db94cbf9ed53d824ddf3356ad67c0b4f4b682eb67a28d919ac
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u18_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u18:latest@sha256:25a53e0b4513a556cb598a92b5f2e7df97701726a6c9db2e01bec0ba2ceded79
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u18_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u18:latest@sha256:d913bd1131521e586446f0fcf48e997d24ee668ee4dad6d619dd4f39dee8b24f
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u20_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:2bfa00dc13383af0e53464a87836f27fd0d052bcf1e358fa753d7a930c893c3c
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u20_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:70111e9aa71b67d3c9ca42ae3ee38e096a843792e197f2d472b2e02af91235df
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u20_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:10bf568356c0fcb2e54f2d294dd61e470eb4c4ec020d3dd97b18b8e35c18e9c3
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u20_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:48c7c043c247906a32aff6bc29c24c839c0fee12eb288871ba394ad05c4146ef
    command: bash -c "sleep infinity"
    volumes: *default-volumes

