# Docker compose file dedicated to Unibuild builds
version: '3.9'

###
# Some repeated defaults:
# tmpfs and /sys/fs/cgroup volumes are needed for systemd to work properly
# /app is where the git repositories will be shared with the host
###
x-tmpfs:
  &default-tmpfs
  - /run
  - /run/lock
  - /tmp

x-volumes:
  &default-volumes
  - ${DIR_TO_BE_BUILT}:/app
 
services:
  alma8:
    image: ghcr.io/perfsonar/unibuild/alma8:latest
    volumes: *default-volumes
  alma9:
    image: ghcr.io/perfsonar/unibuild/alma9:latest
    volumes: *default-volumes
  centos7:
    image: ghcr.io/perfsonar/unibuild/centos7:latest
    volumes: *default-volumes
  d10_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/d10:latest@sha256:b98af337140ce39dd4a3453198e9d6cce0ece970956118b08561183c4018bcfb
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d10_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/d10:latest@sha256:47d791d1fb1dfeeec894db31ce93bb33e5c9c95784a4a564d1ffdf38321f5fdc
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d10_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/d10:latest@sha256:10b7f3136478bc5f388872aecaac1fdff320acd2ce76f7e3c0d9cca74317c4a3
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d10_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/d10:latest@sha256:63eede01bce3fb53bfee7c11d67cc1112a1f574aa9343ac46440c0b06a1bca10
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u18_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u18:latest@sha256:3907b8bff1ce2f02fecdad4b20f65559a847b45859c963b2f27ffa1de9b574a2
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u18_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/u18:latest@sha256:5a66762b24695f4c448efea13b62aa66cbbc8383a5cbca78444cb6433d212366
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u18_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u18:latest@sha256:ae47806c425d0f63580e57df9043dbdbb2b0fd7c1b5f0fcc678c4107b3060945
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u18_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u18:latest@sha256:f027fda012de42fbd06e015c409db40bd70fc3e5ef3be31ac3f044ee00cc75f5
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u20_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:ad2dfe6160e79ef96f672c7afdeb8086fed422ba9dd2aea3926043ee42976508
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u20_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:3c344397a8bba35e4208d19c4601a7808858db1847bd1cfe912dd4b0960e5a42
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u20_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:3ddaf8ecb55d9b168194bac81ae60469f1eddcf66c34ed586cda9d788d3be1a7
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u20_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:4831a3d18fa606d093e88b7d9632b02210e07d299855252aa3540394936814fb
    command: bash -c "sleep infinity"
    volumes: *default-volumes

