# Docker compose file dedicated to Unibuild builds

###
# Some repeated defaults:
# tmpfs and /sys/fs/cgroup volumes are needed for systemd to work properly
# /app is where the git repositories will be shared with the host
###
x-tmpfs:
  &default-tmpfs
  - /run
  - /run/lock
  - /tmp

x-volumes:
  &default-volumes
  - ${DIR_TO_BE_BUILT}:/app
 
services:
  el7:
    image: ghcr.io/perfsonar/unibuild/el7:latest
    volumes: *default-volumes
  el8:
    image: ghcr.io/perfsonar/unibuild/el8:latest
    volumes: *default-volumes
  el9:
    image: ghcr.io/perfsonar/unibuild/el9:latest
    volumes: *default-volumes
  d11_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/d11:latest@sha256:e88f10703603bdb4c2219f4927ec25f8e7e46e8ddfabe262cb0054b8a6b9e461
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d11_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/d11:latest@sha256:ea896be1a4ee3503a551239be455686a86f77ed5b4f9f284a62be0eb5d849346
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d11_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/d11:latest@sha256:8f2d69ee658b169f1dc35f1c036ceb562145b33d8753f2a5cbcebe61450ab080
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d11_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/d11:latest@sha256:1a053804e8be1271387d4b16882327b7b067faa521d4bc913bf88dc4121a3455
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d12_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/d12:latest@sha256:0b1d3f57853f16d7251ac328d670c6af209578550c3b4b9ec48c24ffc7c8c740
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d12_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/d12:latest@sha256:99e071303d3e2470c05a99cf176bdf5460fa0c7fdbf358a0dab02167a3f95e83
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d12_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/d12:latest@sha256:dff9d9cd902df20c4e91a9c357a6d50414f95921f32eea1960f27fdb138dae52
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  d12_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/d12:latest@sha256:e3a0b4e50cbb49a05f422839827d815fa8f1b85317cdf9e2864e6b249786c21a
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u20_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:cb587c42b7d12575c8510c1d09beaa0d52c14523316737f7714b90a7870e000e
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u20_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:da5c3868dfa60912891fd48d11e11d3da67dc49bacc89050f9ff1449b16fc87c
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u20_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:21ca5a06cd71a946ff3c5e0965c4164fa45e8bb0831a0d21c72b568aeffa77ff
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u20_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u20:latest@sha256:8ea06ccff6bd61549531385060cc20b82ac02866f859261cbf74e88de0a1d198
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u22_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u22:latest@sha256:1d9d0cfcef556aa986a771afc2be34989250859a09ecfdbabd3c25bbc8def34e
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u22_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/u22:latest@sha256:16c10426b70e67d22be8c42a732e104b7c94b4319084908cac15cc32ce09203d
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u22_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u22:latest@sha256:561f7d1fa5f633bb856502af26dfad972079841e48750c6caaf4448a3deb56fa
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u22_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u22:latest@sha256:07d866df2906cc2a18d64d8b5b68ac182e10804034ef7ac540145c023da15092
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u24_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u24:latest@sha256:98d77e7dec8c6a96065592ac24fea2d4dcf8852910034fbccaa4fcc1dbb5dc10
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u24_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/u24:latest@sha256:7aa066c088f38f9d8972db716d0f9a021dbeedf21401f75bb8f932b672846d56
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u24_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u24:latest@sha256:98a9787c78bfcc57105cfe74544a9c9e109e2194e83b4e68baca253598ca61b0
    command: bash -c "sleep infinity"
    volumes: *default-volumes
  u24_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u24:latest@sha256:fd95fd2006814a9ab6fd7d8e677b2c25243068441b9b943bdc470298598f4316
    command: bash -c "sleep infinity"
    volumes: *default-volumes

